### ISSUE TITLE
Making Classes Classier, v1

### ISSUE THREAD

**Issue by WJLiddy** [WJLiddy/ad2#3]
Some Ideas to make class playstyles different in AD2. Tell me what you think.

Define Critical as 300~500% Damage

Aksumian - Bonuses:
Merciless:
+20% damage when under quarter health
Rage:
10% chance to critical against enemies who are fleeing
Aksumian - Penalties:
Arrogant: 
Dialogue options are sometimes forced because Aksumian is in party, often leading to combat. 
20% chance incoming projectiles will be critical
Aksumian - Ability 1:
Hammer Throw: Hits all enemies in the surrounding area and launches held weapon. Costs (WeaponRating*5) MP and can only be done with hammers and axes. Triggered by spinning around in a circle twice then hitting "A"

Picarogato - Bonuses:
Sneaky: Guaranteed critical if target is hit from behind with unarmed or melee.
Ninja Skills: 20% chance to steal target's held item if ninja is unarmed and target is idle
Picarogato - Penalties:
Dropout: MP regenerates at half speed
Low Confidence: +25% damage from non-heavy weapons
Picarogato - Ability 1:
Evade: This ability costs 25 MP. If Ninja is Idle, and "B" is pressed right before Ninja takes damage, the damage is subtracted from MP instead of HP.

Majihueja - Bonuses:
Bilingual: Gets exclusive "Spanish Spells" found throughout the game which are considerably stronger than normal spells.
Tough: Damage from all melee sources are reduced by 10%
Magihueja - Penalties:
No Weapons training: All melee weapons are 20% less powerful in the Magihueja's Hands.
Straw Sombrero: Magic Spells do 20% more damage against Magihueja
Magihueja - Ability 1:
Endure: If HP runs out, it is instead set to 1 and damage is multiplied by 2 and deducted from MP instead.

HalfDragon - Bonuses:
Weapon Master: 10% bonus with all weapons.
Armor: 15% Damage resistance when facing an enemy.
HalfDragon - Weaknesses:
Vulnerable wings: Being struck in the back does double damage
Conduction: Magic spells do 20% more damage against Halfdargon
HalfDragon Ability 1:
Fire Shout: When Unarmed, "B" causes Half-Dragon to Breath fire. This can only be triggered when MP is at maximum and cannot be stopped.

**Comment by CorruptData** [comment]
Lots of cool ideas here! It will be cool to see how the game is once they're implemented!

**Comment by WJLiddy** [comment]
They are now implemented.
