### ISSUE TITLE
Enter Covington from south

### ISSUE THREAD

**Issue by WJLiddy** [WJLiddy/ad2#4]
If you enter Covington from the south, you can get stuck in a building.

**Comment by CorruptData** [comment]
Odd issue here. The Covington map in the data folder is correct, but the one in the bin folder is not. For some reason, refreshing Eclipse does not fix this.

**Comment by WJLiddy** [comment]
Have you tried "cleaning" the project. Sometimes works.

**Comment by CorruptData** [comment]
Works. Now clean yours and the map will be fixed.
